### ISSUE TITLE
Can't run function 'eval_test_papers_bert' from bert.py

### ISSUE THREAD

**Issue by moonlightnoodles** [THUDM/paper-source-trace#2]
![problem](https://github.com/THUDM/paper-source-trace/assets/123880310/1a65b877-79b6-49dc-9ee8-c44b1c93cbb7)
can't run function 'eval_test_papers_bert' from bert.py to calculate bert average map due to './paper-source-trace/data/**2023/paper_source_trace_test.json**' is not given.

**Comment by zfjsail** [comment]
Hi, ``eval_test_papers_bert`` is used for the evaluation of an older dataset. Use ``gen_kddcup_valid_submission_bert`` function instead.

**Comment by moonlightnoodles** [comment]
> Hi, `eval_test_papers_bert` is used for the evaluation of an older dataset. Use `gen_kddcup_valid_submission_bert` function instead.

thank you for your reply! but it seems that `eval_test_papers_bert` doesn't calculate MAP value to evaluate this method.
<img width="325" alt="49ba2c45f0dc118c275bd718d3adc16" src="https://github.com/THUDM/paper-source-trace/assets/123880310/ec02a6da-d28b-4f78-9efa-c29c9fd1372f">

**Comment by zfjsail** [comment]
The outputs generated by ``gen_kddcup_valid_submission_bert`` can be submitted to https://www.biendata.xyz/competition/pst_kdd_2024/make-submission/ to obtain the MAP score on the validation set. Currently, since the competition is ongoing, the ground truths of validation set and test set are not provided.

**Comment by moonlightnoodles** [comment]
> The outputs generated by `gen_kddcup_valid_submission_bert` can be submitted to https://www.biendata.xyz/competition/pst_kdd_2024/make-submission/ to obtain the MAP score on the validation set. Currently, since the competition is ongoing, the ground truths of validation set and test set are not provided.

作者你好，虽然比赛已经结束，但我仍然希望在这个任务上进行一些工作，所以能否请您提供实现MAP计算的代码
