### ISSUE TITLE
How to use DBLP?

### ISSUE THREAD

**Issue by moonlightnoodles** [THUDM/paper-source-trace#3]
what is the relationship between this project and the dataset DBLP?

**Comment by zfjsail** [comment]
The papers in the PST dataset are mainly computer science papers. The papers can be matched to DBLP via the paper ID provided in the PST dataset.

**Comment by moonlightnoodles** [comment]
> The papers in the PST dataset are mainly computer science papers. The papers can be matched to DBLP via the paper ID provided in the PST dataset.

Really sorry to bother you. but I don't notice any place in your code where DBLP is utilized

**Comment by zfjsail** [comment]
You can refer to ``net_emb.py``.
