### ISSUE TITLE
Wechat gourp invitation QR code expired

### ISSUE THREAD

**Issue by JamesSand** [THUDM/paper-source-trace#4]
Hi, thank you for your great work.
The QR code for paper reading wechat group is expired. Could you please update the group invitation QR code. Thx

**Comment by moonlightnoodles** [comment]
sry.but what QR code?

**Comment by moonlightnoodles** [comment]
> Hi, thank you for your great work. The QR code for paper reading wechat group is expired. Could you please update the group invitation QR code. Thx

sry.but what QR code?

**Comment by zfjsail** [comment]
Hi You can receive the up-to-date QR code from this channel. https://t.me/+apOrPEOLGixiNjdl

**Comment by JamesSand** [comment]
Thx a lot for ur nice reply!
